# Generated by Django 5.0.9 on 2024-10-18 00:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ModBookApp', '0002_alter_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=150)),
                ('last_name', models.TextField(max_length=150)),
                ('email', models.EmailField(max_length=240, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photo/')),
                ('is_varified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('return_day', models.IntegerField(default=7)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('fine_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason_for_fine', models.CharField(blank=True, choices=[('Delay In Return', 'Delay'), ('Book Loss', 'Loss'), ('Damage Book', 'Damaage')], max_length=50, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModBookApp.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModStudentApp.student')),
            ],
        ),
    ]
