# Generated by Django 5.0.9 on 2024-10-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModStudentApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookBorrow',
        ),
    ]
