# Generated by Django 5.0.9 on 2024-10-25 17:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ModBookApp', '0003_bookstocks'),
        ('ModStudentApp', '0002_delete_bookborrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('return_day', models.IntegerField(default=7)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('fine_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason_for_fine', models.CharField(blank=True, choices=[('Delay In Return', 'Delay'), ('Book Loss', 'Loss'), ('Damage Book', 'Damaage')], max_length=50, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModBookApp.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModStudentApp.student')),
            ],
        ),
    ]
